# frozen_string_literal: true

require "json"
require "set" # rubocop:disable Lint/RedundantRequireStatement -- autoloaded since Ruby 3.2, but be explicit
require_relative "operations"

module Kit
  module Testing
    # The documented example responses Kit::Testing builds from, generated by
    # `rake testing:fixtures` from OPERATIONS and the vendored OpenAPI document
    # (see spec/support/testing_fixtures.rb); a contract test fails when the
    # shipped file differs from what the generator would produce.
    module Fixtures
      PATH = File.expand_path("fixtures.json", __dir__)

      # { "subscribers_get" => { "verb" => "get", "path" => "/v4/subscribers/{id}",
      #   "key" => "subscriber", "kind" => "object" | "list" | "raw" | "none",
      #   "type" => "subscriber", "responses" => { "200" => { "subscriber" => {...} } } }, ... }
      # `type` is the logical response type (see Testing::TYPES): the
      # envelope key alone does not identify one — "stats" is three objects.
      # Recursively freezes a parsed JSON tree (Hashes, Arrays, Strings).
      # Done by hand rather than with `JSON.parse(freeze: true)`: that option
      # arrived in json 2.7, and Ruby 3.2's bundled json (2.6) — which is what
      # `ruby --disable-gems` loads — would silently leave the tree mutable.
      def self.deep_freeze(value)
        case value
        when Hash then value.each_value { |v| deep_freeze(v) }
        when Array then value.each { |v| deep_freeze(v) }
        end
        value.freeze
      end

      # Deep-frozen: a caller reaching in through FIXTURES / .for must not be
      # able to alter a documented example for every later builder call.
      ALL = deep_freeze(JSON.parse(File.read(PATH)))

      # Response type => every field any documented example of that type
      # shows, so an override the canonical example happens to omit
      # (tagged_at on a subscriber) is still accepted, while a typo — or a
      # field of a different type that shares the envelope key — is not.
      KNOWN_FIELDS = ALL.each_value.with_object(Hash.new { |h, k| h[k] = Set.new }) do |fixture, fields|
        type = fixture["type"]
        next unless type

        fixture["responses"].each_value do |body|
          value = body && body[fixture["key"]]
          value = value.first if value.is_a?(Array)
          fields[type].merge(value.keys) if value.is_a?(Hash)
        end
      end.transform_values(&:freeze).freeze

      def self.for(operation)
        ALL.fetch(operation.to_s) do
          raise ArgumentError, "unknown Kit operation #{operation.inspect}; see Kit::Testing::OPERATIONS"
        end
      end

      # The response code to build: the first Kit documents, or `status` when
      # it is one of them.
      def self.status_for(fixture, status)
        codes = fixture["responses"].keys
        return codes.first if status.nil?
        return status.to_s if codes.include?(status.to_s)

        raise ArgumentError, "Kit documents #{codes.join(", ")} for this operation, not #{status}"
      end

      # `overrides` (Symbol or String keys) merged over a copy of `example`
      # (which may be frozen), rejecting a field Kit never documents for this
      # response type. Override values are deep-copied too, so two rows given
      # the same nested Hash stay independent and a frozen value does not
      # leave part of the returned body frozen.
      def self.merge_fields(type, example, overrides)
        overrides.each_with_object(example.dup) do |(field, value), merged|
          name = field.to_s
          unless KNOWN_FIELDS[type].include?(name)
            raise ArgumentError,
                  "#{name.inspect} is not a field of #{type.inspect}; known: #{KNOWN_FIELDS[type].sort.join(", ")}"
          end

          merged[name] = deep_dup(value)
        end
      end

      # An unfrozen deep copy: what builders hand out, so specs may mutate.
      def self.deep_dup(value)
        case value
        when Hash then value.to_h { |k, v| [k, deep_dup(v)] }
        when Array then value.map { |v| deep_dup(v) }
        when String then value.dup
        else value
        end
      end
    end
  end
end
